"""Add category column to ListItem model

Revision ID: 420f78808244
Revises:
Create Date: 2025-06-09 07:30:57.825700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420f78808244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list_item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
